/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iesportada.alquilacarchurriana;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;

/**
 *
 * @author vzh
 */
public class PersonalDataJFrame extends Utils {
    
    Utils utils = new Utils();

    /**
     * Creates new form PersonalDataJFrame
     */
    public PersonalDataJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        dniTextField = new javax.swing.JTextField();
        ccTextField = new javax.swing.JTextField();
        cancelJButton = new javax.swing.JButton();
        cleanJButton = new javax.swing.JButton();
        continueJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        quitJMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alquilacarChurrianaResized100x100.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));
        jPanel1.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 460, -1));
        jPanel1.add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 460, -1));

        ageTextField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();  // ignore event
                }
            }
        });
        jPanel1.add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, -1));

        phoneTextField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();  // ignore event
                }
            }
        });
        jPanel1.add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, -1));
        jPanel1.add(dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 160, -1));

        ccTextField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();  // ignore event
                }
            }
        });
        jPanel1.add(ccTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, -1));

        cancelJButton.setText("Cancelar");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        cleanJButton.setText("Limpiar");
        cleanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cleanJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        continueJButton.setText("Continuar");
        continueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(continueJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Dirección");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel6.setText("DNI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel7.setText("Tarjeta de crédito");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jMenu1.setText("File");

        quitJMenuItem.setText("Exit");
        quitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(quitJMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        aboutJMenuItem.setText("About us");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(aboutJMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanJButtonActionPerformed
        // TODO add your handling code here:
        nameTextField.setText(null);
        addressTextField.setText(null);
        ageTextField.setText(null);
        phoneTextField.setText(null);
        dniTextField.setText(null);
        ccTextField.setText(null);
    }//GEN-LAST:event_cleanJButtonActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        MainJFrame mjf = new MainJFrame();
        mjf.setVisible(true);
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
        // TODO add your handling code here:
        try {
           this.setVisible(true);
           AboutUsJFrame au = new AboutUsJFrame();
           au.setVisible(true);
           au.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        }
        catch (HeadlessException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

    private void quitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitJMenuItemActionPerformed

    private void continueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueJButtonActionPerformed
        // TODO add your handling code here:
        String age = !"".equals(ageTextField.getText()) ? ageTextField.getText() : "0";
        String name = nameTextField.getText();
        String address = addressTextField.getText();
        String phone = phoneTextField.getText();
        String ccNumber = ccTextField.getText();
        String message="";
        String dni = dniTextField.getText();
        boolean error=false;
        utils.setName(name);
        utils.setAge(Integer.parseInt(age));
        utils.setAddress(address);
        utils.setPhone(phone);
        utils.setCCNumber(ccNumber);
        utils.setDNINumber(dni);
        if (!utils.checkEdad()){
            message= message + AGE_WARNING_MESSAGE_ES;
            error = true;
        } 
        if (!utils.checkNameJTextField()){
            message = message + NAME_WARNING_MESSAGE_ES;
            error = true;
        }
        if (!utils.checkAddressJTextField()){
            message = message + ADDRESS_WARNING_MESSAGE_ES;
            error = true;
        }
        if (!utils.checkPhoneJTextField()){
            message = message +PHONE_WARNING_MESSAGE_ES;
            error = true;
        }
        if (!utils.checkCCJTextField()){
            message = message + CC_WARNING_MESSAGE_ES;
            error = true;
        }
        if (!utils.checkDNI()){
            message = message + DNI_WARNING_MESSAGE_ES;
            error = true;
        }
        if (error){
            JOptionPane.showMessageDialog(this, message);
        }
        else {
        BookingVehicleJFrame bvjf = new BookingVehicleJFrame(this, true);
        bvjf.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_continueJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalDataJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalDataJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalDataJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalDataJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalDataJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JTextField ccTextField;
    private javax.swing.JButton cleanJButton;
    private javax.swing.JButton continueJButton;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JMenuItem quitJMenuItem;
    // End of variables declaration//GEN-END:variables
}
